"""Generate a thesis-style LaTeX chapter from persisted workbench studies.

The generator is deliberately conservative: SQLite stores metadata, while time
histories, SRS curves and figures remain file artifacts.  This module turns those
artifacts into a reproducible LaTeX bundle that can be included in a dissertation
or compiled standalone for review.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from railway_simulator.persistence.database import ProjectDatabase
from railway_simulator.persistence.repositories import ProjectRepository, SpectrumRepository, StudyRepository
from railway_simulator.spectrum.service import SpectrumService


@dataclass(frozen=True)
class ChapterBuildResult:
    """Paths generated by :func:`build_latex_chapter`."""

    output_dir: Path
    chapter_tex: Path
    main_tex: Path
    bibliography_bib: Path
    metadata_json: Path
    figures: tuple[Path, ...]
    tables: tuple[Path, ...]


def _latex_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def _safe_float(value: Any) -> float | None:
    try:
        if value is None or value == "":
            return None
        out = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(out):
        return None
    return out


def _format_float(value: Any, ndigits: int = 3) -> str:
    out = _safe_float(value)
    if out is None:
        return "--"
    return f"{out:.{ndigits}f}".rstrip("0").rstrip(".")


def _value_column(frame: pd.DataFrame) -> str:
    if "Feq_MN" in frame.columns:
        return "Feq_MN"
    if "Feq" in frame.columns:
        return "Feq"
    raise KeyError("SRS curve must contain Feq_MN or Feq")


def _load_curve_frame(record: dict[str, Any]) -> pd.DataFrame:
    frame = pd.read_csv(record["curve_csv_path"])
    for key, value in record.items():
        if isinstance(value, (dict, list)):
            continue
        if key not in frame.columns:
            frame.insert(0, key, value)
    return frame


def _curve_label(record: dict[str, Any]) -> str:
    mode = record.get("meta_mode") or record.get("scenario_name") or "scenario"
    speed = _format_float(record.get("meta_speed_kmh"), 0)
    contact = record.get("meta_contact_model") or "contact=?"
    mu = _format_float(record.get("meta_mu"), 2)
    zeta = _format_float(record.get("zeta"), 3)
    return f"{mode}, v={speed} km/h, {contact}, mu={mu}, zeta={zeta}"


def _plot_curves(path: Path, labelled_frames: Iterable[tuple[str, pd.DataFrame]], *, title: str, ylabel: str) -> Path:
    fig, ax = plt.subplots(figsize=(6.8, 4.2))
    any_curve = False
    for label, frame in labelled_frames:
        if "Tn_ms" not in frame.columns or ylabel not in frame.columns:
            continue
        ax.plot(frame["Tn_ms"], frame[ylabel], label=label)
        any_curve = True
    ax.set_xscale("log")
    ax.set_xlabel(r"$T_n$ [ms]")
    ax.set_ylabel(ylabel.replace("_", r"\_"))
    ax.set_title(title)
    ax.grid(True, which="both", alpha=0.35)
    if any_curve:
        ax.legend(fontsize="x-small")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=180)
    plt.close(fig)
    return path


def _write_csv_latex_table(path: Path, frame: pd.DataFrame, *, caption: str, label: str, max_rows: int = 12) -> Path:
    shown = frame.head(max_rows).copy()
    lines = [
        r"\begin{table}[htbp]",
        r"\centering",
        r"\small",
        rf"\caption{{{_latex_escape(caption)}}}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{" + "l" * max(1, len(shown.columns)) + "}",
        r"\toprule",
        " & ".join(_latex_escape(c) for c in shown.columns) + r" \\",
        r"\midrule",
    ]
    for _, row in shown.iterrows():
        values = []
        for value in row.tolist():
            if isinstance(value, float):
                values.append(_format_float(value, 3))
            else:
                values.append(_latex_escape(value))
        lines.append(" & ".join(values) + r" \\")
    if len(frame) > len(shown):
        lines.append(rf"\multicolumn{{{len(shown.columns)}}}{{l}}{{\emph{{Table truncated; see CSV artifact for all rows.}}}} \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _write_bibliography(path: Path) -> Path:
    path.write_text(
        r"""
@techreport{stempniewski2024forbe53,
  author      = {Stempniewski, L. and Labbe, S. and Siegel, S. and Bosch, R.},
  title       = {{\"U}berpr{\"u}fung und Anpassung der Anpralllasten aus dem Eisenbahnverkehr},
  institution = {Deutsches Zentrum f{\"u}r Schienenverkehrsforschung},
  number      = {Forschungsbericht 53},
  year        = {2024},
  doi         = {10.48755/dzsf.240006.01}
}

@standard{cen2006en1991_1_7,
  author = {{CEN}},
  title  = {{EN 1991-1-7}: Eurocode 1 - Actions on structures - Part 1-7: Accidental actions},
  year   = {2006}
}

@standard{cen2003en1991_2,
  author = {{CEN}},
  title  = {{EN 1991-2}: Eurocode 1 - Actions on structures - Part 2: Traffic loads on bridges},
  year   = {2003}
}

@misc{eu2014tsiinf,
  author = {{European Commission}},
  title  = {Commission Regulation (EU) No 1299/2014 on the technical specifications for interoperability relating to the infrastructure subsystem of the rail system in the European Union},
  year   = {2014}
}

@article{lankarani1990contact,
  author  = {Lankarani, H. M. and Nikravesh, P. E.},
  title   = {A contact force model with hysteresis damping for impact analysis of multibody systems},
  journal = {Journal of Mechanical Design},
  volume  = {112},
  number  = {3},
  pages   = {369--376},
  year    = {1990}
}

@inproceedings{bouc1967forced,
  author = {Bouc, R.},
  title  = {Forced vibration of mechanical systems with hysteresis},
  booktitle = {Proceedings of the Fourth Conference on Nonlinear Oscillation},
  year   = {1967}
}

@article{hilber1977hht,
  author  = {Hilber, H. M. and Hughes, T. J. R. and Taylor, R. L.},
  title   = {Improved numerical dissipation for time integration algorithms in structural dynamics},
  journal = {Earthquake Engineering and Structural Dynamics},
  volume  = {5},
  number  = {3},
  pages   = {283--292},
  year    = {1977}
}

@article{flores2011contact,
  author  = {Flores, P. and others},
  title   = {On the continuous contact force models for soft materials in multibody dynamics},
  journal = {Multibody System Dynamics},
  volume  = {25},
  number  = {3},
  pages   = {357--375},
  year    = {2011}
}

@article{hunt1975crossley,
  author  = {Hunt, K. H. and Crossley, F. R. E.},
  title   = {Coefficient of restitution interpreted as damping in vibroimpact},
  journal = {Journal of Applied Mechanics},
  volume  = {42},
  number  = {2},
  pages   = {440--445},
  year    = {1975}
}

@article{bruni2025postderailment,
  author  = {Bruni, S. and others},
  title   = {Numerical simulation of the post-derailment behaviour of a railway vehicle and its interaction with the infrastructure},
  journal = {Multibody System Dynamics},
  volume  = {63},
  number  = {1},
  pages   = {209--234},
  year    = {2025},
  doi     = {10.1007/s11044-024-09990-4}
}

@techreport{bav2011braz,
  author      = {{Bundesanstalt f{\"u}r Verkehr, Unfalluntersuchung Fachbereich Schiene}},
  title       = {Entgleisung des Zuges 46676 am 16. Juni 2010. Arlbergstrecke zwischen Bf Hintergasse und Bf Braz},
  institution = {Bundesanstalt f{\"u}r Verkehr},
  year        = {2011}
}
""".strip()
        + "\n",
        encoding="utf-8",
    )
    return path


def _make_summary_tables(
    *,
    output_dir: Path,
    run_records: list[dict[str, Any]],
    curve_frames: list[pd.DataFrame],
) -> tuple[list[Path], dict[str, Any]]:
    tables_dir = output_dir / "tables"
    tables_dir.mkdir(parents=True, exist_ok=True)
    tables: list[Path] = []
    summary: dict[str, Any] = {}

    run_frame = pd.DataFrame(run_records)
    if not run_frame.empty:
        cols = [c for c in ["meta_vehicle", "meta_mode", "meta_speed_kmh", "meta_contact_model", "meta_mu", "run_status", "elapsed_s"] if c in run_frame.columns]
        short = run_frame[cols].copy() if cols else run_frame.copy()
        short.to_csv(tables_dir / "run_summary.csv", index=False)
        tables.append(_write_csv_latex_table(tables_dir / "run_summary.tex", short, caption="Persisted simulation runs used by the chapter generator.", label="tab:run-summary"))
        summary["n_runs"] = int(len(run_frame))
        summary["n_ok_runs"] = int((run_frame.get("run_status") == "ok").sum()) if "run_status" in run_frame else None
        if "meta_mode" in run_frame:
            summary["modes"] = sorted(str(v) for v in run_frame["meta_mode"].dropna().unique())
        if "meta_contact_model" in run_frame:
            summary["contact_models"] = sorted(str(v) for v in run_frame["meta_contact_model"].dropna().unique())

    if curve_frames:
        long = pd.concat(curve_frames, ignore_index=True)
        long.to_csv(tables_dir / "srs_curves_long.csv", index=False)
        summary["n_srs_points"] = int(len(long))
        summary["n_srs_curves"] = int(len(curve_frames))
        valcol = _value_column(curve_frames[0])
        maxima_cols = [c for c in ["scenario_name", "meta_vehicle", "meta_mode", "meta_speed_kmh", "meta_contact_model", "meta_mu", "zeta"] if c in long.columns]
        if maxima_cols:
            maxima = long.groupby(maxima_cols, dropna=False)[valcol].max().reset_index().sort_values(valcol, ascending=False)
            maxima.to_csv(tables_dir / "srs_maxima.csv", index=False)
            tables.append(_write_csv_latex_table(tables_dir / "srs_maxima.tex", maxima, caption="Maximum equivalent SRS force per persisted curve.", label="tab:srs-maxima"))
            governing = maxima.iloc[0].to_dict() if not maxima.empty else {}
            summary["governing_srs"] = governing
    return tables, summary


def _make_figures(output_dir: Path, records: list[dict[str, Any]], curve_frames: list[pd.DataFrame], *, zeta: float | None) -> tuple[list[Path], dict[str, Any]]:
    figures_dir = output_dir / "figures"
    figures_dir.mkdir(parents=True, exist_ok=True)
    figures: list[Path] = []
    metadata: dict[str, Any] = {}
    if not records or not curve_frames:
        return figures, metadata

    filtered: list[tuple[dict[str, Any], pd.DataFrame]] = []
    for record, frame in zip(records, curve_frames):
        if zeta is not None and abs(float(record.get("zeta", np.nan)) - float(zeta)) > 1.0e-12:
            continue
        filtered.append((record, frame))
    if not filtered:
        filtered = list(zip(records, curve_frames))

    value_col = _value_column(filtered[0][1])
    labelled = [(_curve_label(record), frame) for record, frame in filtered]
    figures.append(_plot_curves(figures_dir / "srs_overlay.png", labelled, title="Persisted SRS curves", ylabel=value_col))

    envelope = SpectrumService.envelope([frame for _, frame in filtered], value_column=value_col)
    envelope_path = figures_dir / "srs_envelope.csv"
    envelope.to_csv(envelope_path, index=False)
    env_col = f"{value_col}_envelope"
    figures.append(_plot_curves(figures_dir / "srs_envelope.png", [("envelope", envelope)], title="SRS envelope", ylabel=env_col))
    metadata["envelope_csv"] = str(envelope_path)

    ratios: list[pd.DataFrame] = []
    groups: dict[tuple[Any, Any, Any, Any, Any], dict[str, pd.DataFrame]] = {}
    for record, frame in filtered:
        key = (
            record.get("meta_vehicle"),
            record.get("meta_speed_kmh"),
            record.get("meta_contact_model"),
            record.get("meta_mu"),
            record.get("zeta"),
        )
        mode = str(record.get("meta_mode"))
        groups.setdefault(key, {})[mode] = frame
    ratio_labelled: list[tuple[str, pd.DataFrame]] = []
    for key, pair in groups.items():
        if "zug_full" not in pair or "lok_solo" not in pair:
            continue
        ratio = SpectrumService.ratio(pair["zug_full"], pair["lok_solo"], value_column=value_col)
        ratio.insert(0, "vehicle", key[0])
        ratio.insert(1, "speed_kmh", key[1])
        ratio.insert(2, "contact_model", key[2])
        ratio.insert(3, "mu", key[3])
        ratio.insert(4, "zeta", key[4])
        ratios.append(ratio)
        ratio_labelled.append((f"{key[0]}, v={key[1]} km/h, {key[2]}, mu={key[3]}", ratio))
    if ratios:
        ratio_df = pd.concat(ratios, ignore_index=True)
        ratio_csv = figures_dir / "srs_full_train_vs_lok_ratio.csv"
        ratio_df.to_csv(ratio_csv, index=False)
        ratio_col = f"{value_col}_ratio"
        figures.append(_plot_curves(figures_dir / "srs_full_train_vs_lok_ratio.png", ratio_labelled, title="Full train / Lok solo SRS ratio", ylabel=ratio_col))
        metadata["ratio_csv"] = str(ratio_csv)
    return figures, metadata


def _latex_chapter_text(
    *,
    title: str,
    author: str,
    study_name: str,
    study_id: str,
    project_name: str,
    n_runs: int,
    n_curves: int,
    figures: tuple[Path, ...],
    tables: tuple[Path, ...],
    output_dir: Path,
    summary: dict[str, Any],
) -> str:
    fig_lines: list[str] = []
    figure_map = {path.name: path for path in figures}
    if "srs_full_train_vs_lok_ratio.png" in figure_map:
        train_effect_text = (
            "Full-consist simulations are retained because they document whether wagon coupling affects "
            "first-contact demand; if the ratio plot in Fig.~\\ref{fig:srs-ratio} is close to unity, "
            "the locomotive-only model governs first-contact peak demand for the selected scenarios."
        )
    else:
        train_effect_text = (
            "Full-consist simulations are retained because they document whether wagon coupling affects "
            "first-contact demand.  No matched full-train/lokomotive SRS ratio figure was available in this "
            "bundle, so this statement must be checked from the persisted curves before drawing a governing "
            "train-effect conclusion."
        )
    for name, caption, label in [
        ("srs_overlay.png", "Shock response spectrum curves generated from the persisted parametric study runs.", "fig:srs-overlay"),
        ("srs_envelope.png", "Envelope of the persisted SRS curves. The envelope is evaluated at the tabulated oscillator periods.", "fig:srs-envelope"),
        ("srs_full_train_vs_lok_ratio.png", "Ratio between full-consist and locomotive-only SRS curves for matched scenarios.", "fig:srs-ratio"),
    ]:
        if name in figure_map:
            rel = figure_map[name].relative_to(output_dir).as_posix()
            fig_lines.extend(
                [
                    r"\begin{figure}[htbp]",
                    r"\centering",
                    rf"\includegraphics[width=0.92\textwidth]{{{rel}}}",
                    rf"\caption{{{caption}}}",
                    rf"\label{{{label}}}",
                    r"\end{figure}",
                    "",
                ]
            )

    table_inputs = []
    for table in tables:
        rel = table.relative_to(output_dir).as_posix()
        table_inputs.append(rf"\input{{{rel}}}")
    table_block = "\n".join(table_inputs) if table_inputs else "% No persisted tables available."

    governing = summary.get("governing_srs") or {}
    governing_text = ""
    if governing:
        value_col = "Feq_MN" if "Feq_MN" in governing else "Feq"
        governing_text = (
            "The largest persisted SRS ordinate in this bundle is "
            f"{_format_float(governing.get(value_col), 3)}~MN for scenario "
            f"{_latex_escape(governing.get('scenario_name', 'n/a'))}."
        )
    else:
        governing_text = "No governing SRS ordinate could be inferred because no persisted SRS curves were selected."

    return rf"""
% Auto-generated by railway_simulator.reporting.latex_chapter.
% Include this file from a thesis root, or compile main.tex in this bundle.
\chapter{{{_latex_escape(title)}}}
\label{{ch:railway-impact-parametric-demand}}

\section{{Motivation and scope}}

Current design practice for accidental railway vehicle impact on trackside structures is commonly anchored to a distance-independent equivalent horizontal force.  In the present work the reference value is denoted by
\begin{{equation}}
F_{{\mathrm{{EN}}}} = 6\,\mathrm{{MN}}.
\end{{equation}}
The purpose of the chapter is not to replace the code value by a single alternative number, but to construct a traceable demand field $F_{{\mathrm{{eq}}}}(a, v_0, \mathrm{{vehicle}})$ over clearance distance, operational speed and vehicle model.  This directly addresses the engineering question of whether the existing assumptions for distances greater than approximately $3\,\mathrm{{m}}$ are adequate, and what load levels are obtained for smaller distances.

The scope is restricted to the first-contact structural demand.  Line-specific derailment frequencies, exposure models, fragility integration and risk aggregation are outside the present chapter and belong to the broader hazard-demand framework.  The persisted study used here is \texttt{{{_latex_escape(study_name)}}} (study id \texttt{{{_latex_escape(study_id)}}}) in project \texttt{{{_latex_escape(project_name)}}}; it contains {n_runs} run records and {n_curves} persisted SRS curves.

\section{{Mechanical model}}

The vehicle is represented as a chain of lumped masses connected by nonlinear Bouc-Wen spring elements.  Wall impact is represented as unilateral contact between the leading vehicle mass and a rigid obstacle, with additional masses allowed to contact the wall during pile-up.  The semi-discrete equation of motion is written as
\begin{{equation}}
M\ddot{{q}} + C\dot{{q}} = R_{{\mathrm{{int}}}} + R_{{\mathrm{{contact}}}} + R_{{\mathrm{{friction}}}} + R_{{\mathrm{{mc}}}},
\label{{eq:eom-impact}}
\end{{equation}}
where $R_{{\mathrm{{int}}}}$ denotes the nonlinear train spring forces, $R_{{\mathrm{{contact}}}}$ the wall contact force, $R_{{\mathrm{{friction}}}}$ the post-derailment sliding resistance and $R_{{\mathrm{{mc}}}}$ the inter-mass penalty contact used during pile-up.  Time integration follows the HHT-$\alpha$ family with numerical dissipation appropriate for high-frequency contact transients \cite{{hilber1977hht}}.

The dissipative Hertz-type contact law used for the baseline Lankarani-Nikravesh model is
\begin{{equation}}
F(\delta,\dot{{\delta}}) = k_w \delta^{{3/2}}\left(1 + \frac{{3(1-c_r^2)}}{{4}}\frac{{\dot{{\delta}}}}{{v_{{c,0}}}}\right), \qquad F \geq 0,
\label{{eq:lankarani-nikravesh}}
\end{{equation}}
where $\delta$ is penetration depth, $\dot{{\delta}}$ is the signed penetration rate, $k_w$ is wall contact stiffness, $c_r$ is the coefficient of restitution and $v_{{c,0}}$ is the contact-birth approach speed \cite{{lankarani1990contact}}.  Alternative dissipative laws such as Flores and Hunt-Crossley are implemented for sensitivity checks \cite{{flores2011contact,hunt1975crossley}}.

\section{{Geometry, runout and wall-normal velocity}}

The impact angle is not treated as an independent free variable at small clearance distances.  For a structure at lateral clearance $a$, the maximum geometrically admissible impact angle is
\begin{{equation}}
\beta_{{\max}}(a) = \arcsin\left(\frac{{a-b/2}}{{\ell_{{\mathrm{{eff}}}}}}\right), \qquad a>b/2,
\label{{eq:beta-max}}
\end{{equation}}
with vehicle width $b$ and effective lever arm $\ell_{{\mathrm{{eff}}}}=(L+d_{{\mathrm{{Dzpa}}}})/2$.  For full train consists an additional consist cap is applied,
\begin{{equation}}
\beta_{{\mathrm{{eff}}}}(a)=\min\left(\beta_{{\max}}(a),\beta_{{\mathrm{{train\ cap}}}}\right).
\label{{eq:beta-eff}}
\end{{equation}}
This geometric filter is the main reason why the demand does not have to be monotonic with decreasing clearance distance.

The residual impact speed after lateral runout is computed from a constant-friction energy balance,
\begin{{equation}}
v_{{\mathrm{{imp}}}} = \sqrt{{\max\left(v_0^2 - \frac{{2\mu g a}}{{\sin\beta_{{\mathrm{{eff}}}}}}, 0\right)}}, \qquad
v_n = v_{{\mathrm{{imp}}}}\sin\beta_{{\mathrm{{eff}}}}.
\label{{eq:runout}}
\end{{equation}}
The parameter $\mu=0.30$ is used as a conservative lower-bound runout assumption for ballasted post-derailment interaction, while larger values may be used in sensitivity studies \cite{{bruni2025postderailment}}.

\section{{Contact-state verification patch}}

The contact implementation uses the sign convention $q_i<0$ for penetration into the wall, $\delta_i=\max(-q_i,0)$ and $\dot{{\delta}}_i=-\dot{{q}}_i$.  Thus $\dot{{\delta}}>0$ during approach and $\dot{{\delta}}<0$ during restitution.  This sign is physically important because the dissipative factor in Eq.~\eqref{{eq:lankarani-nikravesh}} must increase the force during approach and reduce it during unloading.

A previous implementation error affected dissipative models at intermediate-to-high wall-normal velocities.  The contact-active flag was global rather than per mass, so secondary masses entering contact during pile-up could retain the default $v_{{c,0}}=1\,\mathrm{{m/s}}$ instead of their actual contact-birth speed.  In addition, a clipped penetration-rate update removed the restitution branch.  The corrected implementation stores a per-mass contact state and evaluates
\begin{{equation}}
\dot{{\delta}}=-\dot{{q}}, \qquad v_{{c,0}}=|v_{{\mathrm{{birth}}}}|,
\end{{equation}}
with unilateral clamping of tensile contact forces.  The regression suite verifies signed damping direction, tensile clamping and monotonic peak-force sweeps around the previously contaminated velocity range.

\section{{Shock response spectrum post-processing}}

For each persisted time-history run, the equivalent structural demand is evaluated using a single-degree-of-freedom shock response spectrum.  The chapter reports the pseudo-static equivalent force ordinate
\begin{{equation}}
F_{{\mathrm{{eq}}}}(T_n,\zeta)=m_{{\mathrm{{eff}}}}\max_t |\ddot{{u}}(t) + \ddot{{u}}_g(t)|,
\label{{eq:srs-feq}}
\end{{equation}}
where $T_n$ is the oscillator period and $\zeta$ is the damping ratio.  A representative design ordinate may be read at $T_n=100\,\mathrm{{ms}}$, but the full SRS curve is retained in the project database so that sensitivity to structural period remains auditable.

\section{{Persisted study results}}

{table_block}

{governing_text}

{''.join(fig_lines)}

\section{{Interpretation}}

The central design conclusion should be read as conditional on the selected vehicle models, geometric filter, friction assumption and contact law.  The analysis is strongest for relative comparisons across the persisted scenario grid: clearance distance changes both the admissible impact angle and the frictional runout path, so the demand field can peak at an intermediate distance rather than at the closest structure.  {train_effect_text}

\section{{Reproducibility}}

All values in this chapter were generated from the project database and external artifact files rather than hand-edited into the manuscript.  The SQLite database stores project, study, scenario and run metadata; time histories and SRS curves are stored as CSV artifacts with paths recorded in the database.  The report bundle contains the generated \LaTeX{{}} source, bibliography, figures, tabular summaries and a JSON metadata file.  Re-generation is performed with
\begin{{verbatim}}
railway-sim report build-chapter \
  --db project.sqlite \
  --study-id STUDY_ID \
  --output-dir report/chapter
\end{{verbatim}}

\section*{{Chapter note}}

This auto-generated chapter is intended as a thesis-ready technical draft.  It preserves the anti-black-box audit trail: model assumptions, contact-state patch, SRS settings and persisted scenario metadata are stated explicitly, while detailed numerical values remain traceable to CSV artifacts.
""".strip() + "\n"


def _main_tex(chapter_filename: str, bib_filename: str, title: str, author: str) -> str:
    return rf"""
\documentclass[11pt,a4paper]{{report}}
\usepackage[T1]{{fontenc}}
\usepackage[utf8]{{inputenc}}
\usepackage{{lmodern}}
\usepackage{{amsmath,amssymb}}
\usepackage{{booktabs}}
\usepackage{{graphicx}}
\usepackage{{geometry}}
\usepackage{{natbib}}
\usepackage{{hyperref}}
\geometry{{margin=25mm}}
\title{{{_latex_escape(title)}}}
\author{{{_latex_escape(author)}}}
\date{{\today}}
\begin{{document}}
\maketitle
\tableofcontents
\input{{{chapter_filename}}}
\bibliographystyle{{plainnat}}
\bibliography{{{Path(bib_filename).stem}}}
\end{{document}}
""".strip() + "\n"


def build_latex_chapter(
    *,
    db: ProjectDatabase,
    study_id: str,
    output_dir: str | Path,
    title: str = "Parametric Demand Study for Railway Vehicle Impact on Trackside Structures",
    author: str = "S. Labbe",
    zeta: float | None = 0.05,
) -> ChapterBuildResult:
    """Build a reproducible LaTeX report bundle for a persisted study.

    Parameters
    ----------
    db:
        Initialized project database.
    study_id:
        Study identifier in the project database.
    output_dir:
        Directory where the bundle will be written.
    title, author:
        LaTeX title metadata.
    zeta:
        Optional damping-ratio filter for figures.  Tables still include all
        persisted curves so the bundle remains auditable.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    study_repo = StudyRepository(db)
    spectrum_repo = SpectrumRepository(db)
    project_repo = ProjectRepository(db)

    study = study_repo.get_study(study_id)
    project = project_repo.get(study.project_id)
    run_records = study_repo.list_run_records_for_study(study_id)
    curve_records = spectrum_repo.list_curve_records_for_study(study_id)
    curve_frames = [_load_curve_frame(record) for record in curve_records]

    tables, table_summary = _make_summary_tables(output_dir=out, run_records=run_records, curve_frames=curve_frames)
    figures, figure_summary = _make_figures(out, curve_records, curve_frames, zeta=zeta)
    bibliography = _write_bibliography(out / "references.bib")

    metadata = {
        "project_id": project.id,
        "project_name": project.name,
        "study_id": study.id,
        "study_name": study.name,
        "study_type": study.study_type,
        "study_status": study.status,
        "n_run_records": len(run_records),
        "n_srs_curves": len(curve_records),
        "zeta_filter_for_figures": zeta,
        "generated_files": {
            "figures": [str(path) for path in figures],
            "tables": [str(path) for path in tables],
            "bibliography": str(bibliography),
        },
        **table_summary,
        **figure_summary,
    }
    metadata_path = out / "chapter_metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True), encoding="utf-8")

    chapter = out / "chapter_impact_parametric_study.tex"
    chapter.write_text(
        _latex_chapter_text(
            title=title,
            author=author,
            study_name=study.name,
            study_id=study.id,
            project_name=project.name,
            n_runs=len(run_records),
            n_curves=len(curve_records),
            figures=tuple(figures),
            tables=tuple(tables),
            output_dir=out,
            summary=metadata,
        ),
        encoding="utf-8",
    )
    main = out / "main.tex"
    main.write_text(_main_tex(chapter.name, bibliography.name, title, author), encoding="utf-8")

    (out / "README.md").write_text(
        "# Generated LaTeX chapter bundle\n\n"
        "Compile `main.tex` for a standalone review PDF, or include "
        "`chapter_impact_parametric_study.tex` from the thesis root.\n\n"
        "The bundle was generated from the project database and persisted CSV/PNG artifacts.\n",
        encoding="utf-8",
    )

    return ChapterBuildResult(
        output_dir=out,
        chapter_tex=chapter,
        main_tex=main,
        bibliography_bib=bibliography,
        metadata_json=metadata_path,
        figures=tuple(figures),
        tables=tuple(tables),
    )
