"""Hazard-informed analysis package for railway impact simulator."""
from .runout import (
    kmh_to_ms,
    ms_to_kmh,
    max_lateral_reach_m,
    runout_path_length_m,
    impact_velocity_ms,
    normal_velocity_ms,
    bounded_weibull_reach_probability,
)
from .rate import (
    base_occurrence_rate_per_year,
    scenario_occurrence_rate,
    lambda_en_crit,
    iso_demand_mask,
    exceedance_mask,
)
from .metamodel import (
    get_default_coeffs,
    power_law_feq,
    fit_power_law,
    PowerLawCoeffs,
)
from .sdof import (
    equivalent_static_force_sdof,
    compute_response_spectrum,
    termination_ratio,
    force_history_is_terminated,
)
from .engine_bridge import (
    build_one_mass_hooke_engine_params,
    extract_engine_force_history,
    equivalent_static_force_from_engine_df,
)

from .lateral import (
    SDOFSettings,
    EquivalentDemandResult,
    VelocityFamily,
    MechanismWeights,
    ScenarioExceedanceResult,
    build_single_mass_reference_params,
    lateral_initial_coordinates,
    estimate_t_last_s,
    lateral_t_max_s,
    build_lateral_yaw_params,
    wall_reaction_histories_N,
    equivalent_demands_from_wall_reactions,
    equivalent_demands_from_engine_df,
    single_mass_reference_feq_MN,
    default_velocity_families,
    scenario_weight_grid,
    scenario_grid,
    scenario_exceedance_from_vstar,
    grid_summary,
)
from .montecarlo import (
    MCParams,
    forward_mc,
    inverse_iso_demand_region,
    sample_mc_scenarios,
)


from .deterministic import (
    DEFAULT_GUIDANCE_THRESHOLD_MS,
    LogPchipResponseProvider,
    ResponseMetrics,
    beta_crit_deg,
    compact_summary_table,
    deterministic_runout_grid,
    deterministic_runout_row,
    lateral_regime_label,
)

__all__ = [
    "kmh_to_ms",
    "ms_to_kmh",
    "max_lateral_reach_m",
    "runout_path_length_m",
    "impact_velocity_ms",
    "DEFAULT_GUIDANCE_THRESHOLD_MS",
    "LogPchipResponseProvider",
    "ResponseMetrics",
    "beta_crit_deg",
    "compact_summary_table",
    "deterministic_runout_grid",
    "deterministic_runout_row",
    "lateral_regime_label",
    "normal_velocity_ms",
    "bounded_weibull_reach_probability",
    "base_occurrence_rate_per_year",
    "scenario_occurrence_rate",
    "lambda_en_crit",
    "iso_demand_mask",
    "exceedance_mask",
    "get_default_coeffs",
    "power_law_feq",
    "fit_power_law",
    "PowerLawCoeffs",
    "equivalent_static_force_sdof",
    "compute_response_spectrum",
    "termination_ratio",
    "force_history_is_terminated",
    "build_one_mass_hooke_engine_params",
    "extract_engine_force_history",
    "equivalent_static_force_from_engine_df",
    "MCParams",
    "forward_mc",
    "inverse_iso_demand_region",
    "sample_mc_scenarios",
    "SDOFSettings",
    "EquivalentDemandResult",
    "VelocityFamily",
    "MechanismWeights",
    "ScenarioExceedanceResult",
    "build_single_mass_reference_params",
    "lateral_initial_coordinates",
    "estimate_t_last_s",
    "lateral_t_max_s",
    "build_lateral_yaw_params",
    "wall_reaction_histories_N",
    "equivalent_demands_from_wall_reactions",
    "equivalent_demands_from_engine_df",
    "single_mass_reference_feq_MN",
    "default_velocity_families",
    "scenario_weight_grid",
    "scenario_grid",
    "scenario_exceedance_from_vstar",
    "grid_summary",
]
